import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
const root = new URL('../', import.meta.url);
export async function shellFiles() {
  const files = ['index.html', 'badk-live-dashboard.html', 'install.html', 'manifest.webmanifest'];
  for (const dir of ['js', 'assets', 'icons']) {
    for (const entry of await readdir(new URL(dir, root), { recursive: true, withFileTypes: true })) {
      if (entry.isFile()) files.push(fileURLToPath(new URL(entry.name, 'file://' + entry.parentPath + '/')).slice(fileURLToPath(root).length));
    }
  }
  return files.sort();
}
export async function generateWorker() {
  const files = await shellFiles();
  const runtime = await readFile(new URL('sw-runtime.js', import.meta.url), 'utf8');
  const hash = createHash('sha256').update(runtime);
  for (const file of files) hash.update(file).update(await readFile(new URL(file, root)));
  return `// Generated by npm run prepare:sw. Do not edit directly.\nconst REVISION = ${JSON.stringify(hash.digest('hex').slice(0, 16))};\nconst SHELL = ${JSON.stringify(['./', ...files.map(f => './' + f)], null, 2)};\n${runtime}`;
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await writeFile(new URL('sw.js', root), await generateWorker());
  console.log('Service worker manifest updated.');
}
